spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/AutoBase
    username: sa
    password: admin
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: sa
    password: admin
    schemas: public
    url: jdbc:postgresql://localhost:5437/AutoBase

data:
  cities: src/main/resources/cities.txt
  cars: src/main/resources/cars.txt
  names: src/main/resources/names.txt
  lastnames: src/main/resources/lastnames.txt
  cargoTypes: src/main/resources/cargoTypes.txt

value:
  averageCarSpeed: 100
  title: "My AutoBase"